feat: OS-14993 Make redirects from one file to another transparent
brightsign/electron pull request #12
Opened 2023-03-15 18:37 UTC by t-bashir-bs

#### Description of Change

This change will trigger a 'transparent' redirect if we have a file url and onBeforeRequest is
passed a redirection url that is also a file. A transparent redirection means simply changing
the source url. 
Method RestartInternal makes the call to OnBeforeRequest and passes a callback, which
is ContinueToBeforeSendHeaders for the non header client case. We add a check
to ContinueToBeforeSendHeaders to see if redirect_url_ is set and it and the source url
are using file schema.  If this occurs the source url is set to redirect_url_ and redirect_url_ 
is cleared to prevent a normal redirect from occurring.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes:

2023-03-15 20:08 UTC, caneraltinbasak approved these changes

2023-03-15 20:46 UTC, caneraltinbasak requested changes
After approving your change, I've noticed you don't have a test case. Change looks ok and it is basic, but just to make sure we don't lose the functionality for one reason or another(ex: when we do electron updates), can you please add a basic test case into api-net-spec.ts to test this.
Your test can assert if callback is run more than once after redirect...

2023-03-17 14:55 UTC, t-bashir-bs commented
> After approving your change, I've noticed you don't have a test case. Change looks ok and it is basic, but just to make sure we don't lose the functionality for one reason or another(ex: when we do electron updates), can you please add a basic test case into api-net-spec.ts to test this.
> Your test can assert if callback is run more than once after redirect...

Done, test case added to api-web-request-spec.ts as that was a more appropriate place to add it.

2023-03-17 17:15 UTC, caneraltinbasak approved these changes

2023-03-17 17:41 UTC, merged